# Site settings
title: SSTT.CF 
description: SST t website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sstt.cf" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: knthb
user_description: member of sstctf
email: kenneth@sstctf.org
twitter_username: SSTCTF
github_username:  knthb


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
gems:
  - jemoji
  - jekyll-mentions
  
emoji:
  src: "/assets"
